server.port=8080
spring.application.name=koursekit

# Database Configuration with Placeholders, the placeholders are replaced with the values in the .env file (needs a little configuration)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# JWT Configuration
jwt.secret=${JWT_SECRET}
jwt.expiration=259200000
jwt.expiration.remember=2592000000

# Email Configuration
spring.mail.username=koursekit@gmail.com
spring.mail.password=oxijarwjyrxsautn

# These are for the custom 'EmailConfig' class
email.username=koursekit@gmail.com
email.password=oxijarwjyrxsautn

# Rate Limiting
ratelimit.login.max=5
ratelimit.login.window=60
ratelimit.signup.max=3
ratelimit.signup.window=300

# OpenAI API
openai.api.key=${OPENAI_API_KEY}

# Multipart file upload
file.upload-dir=./uploads
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# JPA/Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database=mysql
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.main.allow-circular-references=true
